ARCH=sandbox
APP=apps/baremetal/fossa-demo
EXTRA_CFLAGS:=
CROSS_COMPILE?=
CC=gcc
PICOTCP_FLAGS:=IPV4=1 IPV6=1 ETH=1 TCP=1 UDP=1 IPFRAG=1 ICMP4=1 MCAST=1 DNS_CLIENT=1
PICOTCP_FLAGS+= DEVLOOP=0 CRC=0 NAT=0 PING=0 DHCP_CLIENT=0 DHCP_SERVER=0 IPFILTER=0 OLSR=0 SLAACV4=0 SNTP_CLIENT=0 TFTP=0
LWIP_FLAGS:= 
LIBHTTP_FLAGS= 
LIBPICOWEBSOCKET_FLAGS= 
LIBPICOWEBSOCKET_BSD_FLAGS= 
PREFIX=/home/vinz/tass-connected-devices/out
EXTRA_CFLAGS+=-I/home/vinz/tass-connected-devices -DSINGLE_THREADED -DREPLACE_STDCALLS -DPICOTCP=1 -DSANDBOX -g -ggdb -O0
FPU=
